export const MODAL_ACTION_CONFIRM = "MODAL_ACTION_CONFIRM";
export const MODAL_ACTION_CLOSE = "MODAL_ACTION_CLOSE";
export const ACTION_REMOVE = "ACTION_REMOVE";
export const ACTION_UPDATE = "ACTION_UPDATE";
export const ACTION_ADD = "ACTION_ADD";
